
default:
	chmod +x build.sh && ./build.sh

libsdlmain:
	chmod +x build-libSDLMain.sh && ./build-libSDLMain.sh
	
macappstore:
	chmod +x build_macappstore.sh && build_macappstore.sh

clean:
	chmod +x clean.sh && ./clean.sh
